version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "9001:9001"
    depends_on:
      - order
      - payment

  order:
    build: ./order
    ports:
      - "8081:8081"

  payment:
    build: ./payment
    ports:
      - "8082:8082"