name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push api-gateway Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Build and push order Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./order
          file: ./order/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order:latest

      - name: Build and push payment Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./payment
          file: ./payment/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment:latest
